##
# Jump App Microservices Chart values
#
# DEV environment
#
##

# Subcharts status
jump-app-cicd:
  enabled: false

jump-app-argocd:
  enabled: false

jump-app-micros:
  enabled: false

jump-app-ocp-bootstrap:
  render: true
  enabled: true
  ocpversion:
    enabled: false
    channel: "stable-4.11"
    clusterID: "9e157d8b-c2c8-4fdf-903b-85ab4488ad21"
    image: "quay.io/openshift-release-dev/ocp-release@sha256:01c9ef7f802f0ba254847c22e960cd6453ed9f61d9296fdda8bd497712f53e23"
    version: "4.11.16"
  namespaces:
    - jump-app-cicd
    - openshift-marketplace
    - openshift-operators
    - bootstrap
    - knative-serving
    - mesh-test
    - jump-app-dev
    - jump-app-pre
    - jump-app-pro
  argocd:
    enabled: true
    controller: openshift-gitops
  catalogsources:
    jumpapp:
      enabled: true
      image: registry.redhat.io/redhat/certified-operator-index:v4.11
      publiser: Asier
  operators:
    tekton:
      enabled: true
      channel: latest
      approval: Automatic
      name: openshift-pipelines-operator-rh
      # csv: openshift-pipelines-operator-rh.v1.8.0
      source: redhat-operators
      sourcenamespace: openshift-marketplace
    knative:
      enabled: true
      channel: stable
      approval: Automatic
      name: serverless-operator
      # csv: serverless-operator.v1.24.0
      source: redhat-operators
      sourcenamespace: openshift-marketplace
    kiali:
      enabled: true
      channel: stable
      approval: Automatic
      name: kiali-ossm
      # csv: kiali-operator.v1.48.3
      source: redhat-operators
      sourcenamespace: openshift-marketplace
    jaeger:
      enabled: true
      channel: stable
      approval: Automatic
      name: jaeger-product
      # csv: jaeger-operator.v1.38.0-2
      source: redhat-operators
      sourcenamespace: openshift-marketplace
    servicemesh:
      enabled: true
      channel: stable
      approval: Automatic
      name: servicemeshoperator
      # csv: servicemeshoperator.v2.2.3
      source: redhat-operators
      sourcenamespace: openshift-marketplace
    gitops:
      enabled: false
      channel: stable
      approval: Automatic
      name: openshift-gitops-operator
      # csv: openshift-gitops-operator.v1.5.6-0.1664915551.p
      source: redhat-operators
      sourcenamespace: openshift-marketplace
  istio:
    enabled: true
    namespace: istio-system
    controlplane: basic
    argocd:
      controller: openshift-gitops
    smcp:
      istiod:
        replicas: 1
      gateways:
        ingress:
          replicas: 1
        egress:
          replicas: 1
      version: v2.3
    smmr:
      namespaces:
      - mesh-test
      - jump-app-dev
      - jump-app-pre
      - jump-app-pro
  knative:
    enabled: true
    eventing:
      enabled: true
    serving:
      enabled: true
