apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/acidonper/jump-app-kustomize/istio/?ref=master
configMapGenerator:
  - name: react-envs
    behavior: merge
    literals:
    - REACT_APP_BACK=https://back-golang-istio-system.apps.cluster1.sandbox1324.opentlc.com/jump
patches:
  - path: patch-gw-back-golang.yaml
    target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: back-golang
  - path: patch-gw-front-javascript.yaml
    target:
      group: networking.istio.io
      version: v1alpha3
      kind: Gateway
      name: front-javascript
  - path: patch-vs-back-golang.yaml
    target:
      group: networking.istio.io
      version: v1alpha3
      kind: VirtualService
      name: back-golang
  - path: patch-vs-front-javascript.yaml
    target:
      group: networking.istio.io
      version: v1alpha3
      kind: VirtualService
      name: front-javascript