apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/acidonper/jump-app-kustomize/micros/?ref=master
configMapGenerator:
  - name: react-envs
    behavior: merge
    literals:
    - REACT_APP_BACK=https://back-golang-kustomize-test.apps.cluster1.sandbox1324.opentlc.com/jump